import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./components/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dan Saviour Corp.",
  description: "Generated by Dansaviour Corp.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
